### ISSUE TITLE
Issue in `List.AddEntry` and `List.SetEntries`

### ISSUE THREAD

**Issue by xescugc** [mcarpenter622/ebitenui#136]
I've written a small example in https://github.com/xescugc/ebitenui-list just run `go run .`.

Basically when elements are added with `SetEntries` they do not respond to any action. They cannot be selected/hovered ... anything, nothing works.

On the example you can see 2 lists, 1 is updated with `AddEntry` on the `Draw` and the other is updated with `SetEntries` on the `Draw`  too.

**Comment by mcarpenter622** [comment]
So the reason nothing is working is because the SetEntries is getting called 60 times a second, and each time it is resetting the list to its default state. That means nothing will be selected. You shouldn't be adding or updating the list like that in the draw loop. Essentially SetEntries is doing exactly what it is supposed to do. The only reason the one with AddEntry is working like you're expecting is because it has some deduplication code so that you dont add the same item to the list multiple times. 

While testing that I did notice that my dedup code is busted so I'll be fixing that, but other than that, this is working as expected. My recommendation for you is to call SetEntries from a button or something like that..

**Comment by xescugc** [comment]
Ok perfect :) Would be good to add it to the `godoc` as the description of `SetEntries` and `AddEntry` is "the same" so from my PoV it looked like one is just an easy way to set multiple Entries at once.

If you want to close the issue feel free to do it or if you want to wait to fix the `dedup` code you mentioned

**Comment by mcarpenter622** [comment]
Fixed
