### ISSUE TITLE
Maybe add some alias to PreferredSizeLocateableWidget?

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#46]
Since most of the time it looks like we need `widget.PreferredSizeLocateableWidget` for `AddChild()` argument, perhaps there could be a shorthand for `widget.PreferredSizeLocateableWidget`? It can't be `widget.Widget`, since that name is already used, but the current way of spelling "an arbitrary widget that can be a child of another widget" is quite verbose and not very intuitive.

This is just a suggestion though. The library users can define an alias on their own like:
```go
type Widget = widget.PreferredSizeLocateableWidget
```

Why do we even need to spell that type in the first place? Well, mostly when you want to define some sort of a factory function that may return an arbitrary UI widget. Any forms of abstractions on top of widgets would like to avoid spelling the concrete widget type directly in my opinion. If we want to have a collection of widgets (a slice), it should also be more concise to say `[]Widget` (our local type alias) instead of `[]ebitenui.PreferredSizeLocateableWidget` but having a library-bundled alias could make writing tutorials a little bit easier.

Note that `widget.PreferredSizeLocateableWidget` is used inside the `examples/demo` too. So it's not a totally artificial use case. :)

**Comment by mcarpenter622** [comment]
I've been using HasWidget as the primary alias interface within the library. This seems to work quite well.  At this point I don't plan to make any changes to the library for this since I believe it to be sufficient. Please feel free to reopen this ticket if you feel very strongly about this and have any additional suggestions about it.

Thank you for your care about this library!
